language: java
service: docker
notifications:
  email:
    - ro.franchini@gmail.com

before_install:
  - docker version
  - docker info

script:
  - ./mvnw clean install docker:build -fae

jdk:
  - openjdk8
