############################################################
# Dockerfile to run an OrientDB (Graph) Container
# for current developed version
############################################################

FROM azul/zulu-openjdk:8

MAINTAINER Roberto Franchini (ro.franchini@gmail.com)

ADD twitter-fetcher.jar /

CMD ["java"]
