############################################################
# Dockerfile to run an OrientDB (Graph) Container
# for current developed version
############################################################

FROM azul/zulu-openjdk:8

MAINTAINER OrientDB LTD (info@orientdb.com)

ADD twitter-fetcher.jar /

CMD ["java"]
